### ISSUE TITLE
reasonable build system

### ISSUE THREAD

**Issue by ericbmerritt** [erlware/erlmarkdown#2]
erlmarkdown needs a reasonable rebar based build system that runs both dialzyer and tests.

**Comment by badosu** [comment]
There is the `next` branch.

But it downloads the rebar binary where it should just use one if it is available.

See https://github.com/badosu/coil/issues/2

**Comment by ericbmerritt** [comment]
@badosu next branch needs to go away. This project needs to be brought up to the erlware standards and we just have not done that as yet.
